CREATE TABLE IF NOT EXISTS PRODUCTS (
   productId BIGINT NOT NULL, 
   name VARCHAR(500) NOT NULL, 
   price DECIMAL NOT NULL, 
   version INT NOT NULL, 
   latest BOOLEAN
);

CREATE VIEW IF NOT EXISTS ACTIVE_PRODUCTS
AS
SELECT * FROM PRODUCTS WHERE latest = TRUE;

CREATE TABLE IF NOT EXISTS ORDERS (
   orderId BIGINT PRIMARY KEY NOT NULL,
   buyerEmailId VARCHAR(500) NOT NULL,
   orderTime TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERS_PRODUCTS (
  orderId BIGINT NOT NULL,
  productId BIGINT NOT NULL,
  version INT NOT NULL, 
  foreign key (orderId) references ORDERS(orderId),
  foreign key (productId, version) references PRODUCTS(productId, version)
);


CREATE SEQUENCE IF NOT EXISTS SQ_PRODUCT_ID;
CREATE SEQUENCE IF NOT EXISTS SQ_ORDER_ID;


CREATE INDEX IF NOT EXISTS PRODUCT_LATEST ON PRODUCTS(PRODUCTID, LATEST);
CREATE INDEX IF NOT EXISTS PRODUCT_ID_INDEX ON PRODUCTS(PRODUCTID);
CREATE INDEX IF NOT EXISTS ORDER_PRODUCT_INDEX ON ORDERS_PRODUCTS(ORDERID);
CREATE INDEX IF NOT EXISTS ORDER_PRODUCT_ALL_INDEX ON ORDERS_PRODUCTS(PRODUCTID, ORDERID, VERSION);